name: socialgraphs
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0
  - aom=3.9.1
  - asttokens=3.0.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - click=8.2.1
  - colorama=0.4.6
  - comm=0.2.1
  - cycler=0.12.1
  - dav1d=1.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.7.1
  - fontconfig=2.14.1
  - freeglut=3.4.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - getopt-win32=0.1
  - glib=2.84.2
  - glib-tools=2.84.2
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gts=0.7.6
  - harfbuzz=10.2.0
  - icu=73.2
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - joblib=1.5.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.3.0
  - libavif16=1.3.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libgd=2.3.3
  - libglib=2.84.2
  - libhwloc=2.12.1
  - libiconv=1.18
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.7.0
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.8
  - llvm-openmp=21.1.4
  - lz4-c=1.9.4
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.6
  - mkl=2025.3.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - nest-asyncio=1.6.0
  - nltk=3.9.2
  - numpy-base=2.3.4
  - openjpeg=2.5.2
  - openssl=3.5.4
  - packaging=25.0
  - pango=1.50.7
  - parso=0.8.4
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.19.1
  - pygraphviz=1.14
  - python=3.12.11
  - python-dateutil=2.9.0post0
  - pywin32=311
  - pyzmq=26.2.0
  - rav1e=0.7.1
  - regex=2025.9.1
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.2.0
  - svt-av1=3.1.2
  - tbb=2022.3.0
  - tk=8.6.15
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - wheel=0.45.1
  - wordcloud=1.9.4
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - beautifulsoup4==4.14.2
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - contourpy==1.3.3
      - feedparser==6.0.12
      - fonttools==4.59.2
      - idna==3.10
      - kiwisolver==1.4.9
      - mpmath==1.3.0
      - mwparserfromhell==0.7.2
      - networkx==3.5
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - pandas==2.3.2
      - powerlaw==1.5
      - pydot==4.0.1
      - pyparsing==3.2.3
      - pytz==2025.2
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.16.1
      - seaborn==0.13.2
      - sgmllib3k==1.0.0
      - soupsieve==2.8
      - threadpoolctl==3.6.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - wikipedia-api==0.8.1
prefix: C:\Users\sofie\anaconda3\envs\socialgraphs
